version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: db_migrations
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: db_migrations
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4
    container_name: db_migrations_project-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: root@kpi.edu
      PGADMIN_DEFAULT_PASSWORD: password123
    ports:
      - "8080:80"

volumes:
  pgdata:
